language: node_js
node_js:
  - "6"
env:
    global:
      - ENCRYPTION_LABEL: "fdfda14a8651"
      - COMMIT_AUTHOR_EMAIL: "thomas.sauvajon.dev@gmail.com"
      - CI=true
      - NODE_ENV=production
script:
  - yarn test
  - yarn lint
  - bash ./.travis-deploy.sh
