language: node_js
node_js:
  - "6"
env:
    global:
      - ENCRYPTION_LABEL: "fdfda14a8651"
      - COMMIT_AUTHOR_EMAIL: "thomas.sauvajon.dev@gmail.com"
      - CI=true
      - NODE_ENV=production
script:
  - yarn lint
  - yarn test:once
  - yarn build
  - bash ./.travis-server.sh
  # - yarn export:coverage
  # - bash ./.travis-deploy.sh
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#   local_dir: build
#   on:
#     branch: master
