language: node_js
node_js:
  - "6"
env:
  - CI=true
    global:
      - NODE_ENV=production
      - GH_REF: github.com/tsauvajon/epsi-echec-client
      - GH_TOKEN: 0c1e4ddcaa129a51287f216419fad0f4345d36c5
      - secure: d0Jm5eDSBzH9YkPFMSu+Xn35Xh11YZKKJsqKQTmwufFl2wJWyKYGcWBNZNZZERBxqUuXVKynswJMzVX2dI28qX9X3/r/TMlVtQaoTICZ3jebEP5T7RW5+VsQp98C4YnaEN1+hyxs0wwnxwuY5edGGJl6uUxc5OOBKW4LTo2JYyg/o/WEIZzckcgvE9SPPg3KXkuwTnXOINq2IHs0TFepvHsLZBO4siaiKBV/lxVVTBcE+8ikatsFjZ5o2Xj97V6G7qSCIYLOCr191JUCwF58IqIYbmnYTjvFYBtd5lTJJEiEJlrmduRUvVbOug6jJ9o81iYUrADs0F4uGmxAfZ8S8SaSy1oyFZA9GQYfDSDb+hDLSwaeHNMPHcc/bRWym3kdhdFVjgjLUQxvApEMKmgprhR2N2uP//u3PE7QOfhIBZ4j367N+teUbob57TFfHmi5Ylo0qv5WAGXgsmbLo9yiXAICxhIpkngEjrMdB+JVB7xNxj5rwdWzCCbF2dO3eN1OSIYyDILpkg6u6I71AfkZ3SLxGl6kfhDgp+FXOA5KFWHZh15nsW8gY68vnuKqRJXBxDepGNPPN91ufQaabc2jq9/vYiKWpTbBGN7aJJgHdGL9jYTk4vyvLB50kzP/3OvlyWgtRy7DPGTlOhOiINRFR8chhtorUpTAXeX+uvRWn+o=
script:
  - npm test
  - npm run lint
  - npm run deploy

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: ./scripts/deploy.sh
#   on:
#     branch: master
#     node: '6'
